services:
  app:
    image: v1adhope/music-artist-service:v0.0.1
    restart: always
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        restart: true
        condition: service_healthy
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: rat
      POSTGRES_DB: music_artist_service
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
