// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: api/proto/v1/artist.proto

package artistv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtistType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name              string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Website           string  `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	MounthlyListeners uint64  `protobuf:"varint,5,opt,name=mounthly_listeners,json=mounthlyListeners,proto3" json:"mounthly_listeners,omitempty"`
	Email             string  `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Status            *string `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *ArtistType) Reset() {
	*x = ArtistType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_artist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtistType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistType) ProtoMessage() {}

func (x *ArtistType) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistType.ProtoReflect.Descriptor instead.
func (*ArtistType) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artist_proto_rawDescGZIP(), []int{0}
}

func (x *ArtistType) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ArtistType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtistType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArtistType) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *ArtistType) GetMounthlyListeners() uint64 {
	if x != nil {
		return x.MounthlyListeners
	}
	return 0
}

func (x *ArtistType) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ArtistType) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type ArtistIdType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ArtistIdType) Reset() {
	*x = ArtistIdType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_artist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtistIdType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistIdType) ProtoMessage() {}

func (x *ArtistIdType) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistIdType.ProtoReflect.Descriptor instead.
func (*ArtistIdType) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artist_proto_rawDescGZIP(), []int{1}
}

func (x *ArtistIdType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArtistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ArtistIdType `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetArtistReq) Reset() {
	*x = GetArtistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_artist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArtistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistReq) ProtoMessage() {}

func (x *GetArtistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistReq.ProtoReflect.Descriptor instead.
func (*GetArtistReq) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artist_proto_rawDescGZIP(), []int{2}
}

func (x *GetArtistReq) GetData() *ArtistIdType {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetArtistReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ArtistType `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetArtistReply) Reset() {
	*x = GetArtistReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_artist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArtistReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistReply) ProtoMessage() {}

func (x *GetArtistReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistReply.ProtoReflect.Descriptor instead.
func (*GetArtistReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artist_proto_rawDescGZIP(), []int{3}
}

func (x *GetArtistReply) GetData() *ArtistType {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllArtistReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ArtistType `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllArtistReply) Reset() {
	*x = GetAllArtistReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_artist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllArtistReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllArtistReply) ProtoMessage() {}

func (x *GetAllArtistReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllArtistReply.ProtoReflect.Descriptor instead.
func (*GetAllArtistReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artist_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllArtistReply) GetData() []*ArtistType {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateArtistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ArtistType `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateArtistReq) Reset() {
	*x = CreateArtistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_artist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArtistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtistReq) ProtoMessage() {}

func (x *CreateArtistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtistReq.ProtoReflect.Descriptor instead.
func (*CreateArtistReq) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artist_proto_rawDescGZIP(), []int{5}
}

func (x *CreateArtistReq) GetData() *ArtistType {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateArtistReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ArtistIdType `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateArtistReply) Reset() {
	*x = CreateArtistReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_artist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArtistReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtistReply) ProtoMessage() {}

func (x *CreateArtistReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtistReply.ProtoReflect.Descriptor instead.
func (*CreateArtistReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artist_proto_rawDescGZIP(), []int{6}
}

func (x *CreateArtistReply) GetData() *ArtistIdType {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReplaceArtistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ArtistType `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReplaceArtistReq) Reset() {
	*x = ReplaceArtistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_artist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceArtistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceArtistReq) ProtoMessage() {}

func (x *ReplaceArtistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceArtistReq.ProtoReflect.Descriptor instead.
func (*ReplaceArtistReq) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artist_proto_rawDescGZIP(), []int{7}
}

func (x *ReplaceArtistReq) GetData() *ArtistType {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteArtistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ArtistIdType `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteArtistReq) Reset() {
	*x = DeleteArtistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_artist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteArtistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtistReq) ProtoMessage() {}

func (x *DeleteArtistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtistReq.ProtoReflect.Descriptor instead.
func (*DeleteArtistReq) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artist_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteArtistReq) GetData() *ArtistIdType {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_proto_v1_artist_proto protoreflect.FileDescriptor

var file_api_proto_v1_artist_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xe5, 0x01, 0x0a, 0x0a, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65,
	0x62, 0x73, 0x69, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62,
	0x73, 0x69, 0x74, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x68, 0x6c, 0x79,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x11, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1e, 0x0a, 0x0c, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x49, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x38, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3b, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x3b, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x49, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xb0, 0x02, 0x0a,
	0x06, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x14,
	0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x06,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19,
	0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17,
	0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42,
	0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x31,
	0x61, 0x64, 0x68, 0x6f, 0x70, 0x65, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2d, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x3b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_v1_artist_proto_rawDescOnce sync.Once
	file_api_proto_v1_artist_proto_rawDescData = file_api_proto_v1_artist_proto_rawDesc
)

func file_api_proto_v1_artist_proto_rawDescGZIP() []byte {
	file_api_proto_v1_artist_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_artist_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_v1_artist_proto_rawDescData)
	})
	return file_api_proto_v1_artist_proto_rawDescData
}

var file_api_proto_v1_artist_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_v1_artist_proto_goTypes = []any{
	(*ArtistType)(nil),        // 0: artist.ArtistType
	(*ArtistIdType)(nil),      // 1: artist.ArtistIdType
	(*GetArtistReq)(nil),      // 2: artist.GetArtistReq
	(*GetArtistReply)(nil),    // 3: artist.GetArtistReply
	(*GetAllArtistReply)(nil), // 4: artist.GetAllArtistReply
	(*CreateArtistReq)(nil),   // 5: artist.CreateArtistReq
	(*CreateArtistReply)(nil), // 6: artist.CreateArtistReply
	(*ReplaceArtistReq)(nil),  // 7: artist.ReplaceArtistReq
	(*DeleteArtistReq)(nil),   // 8: artist.DeleteArtistReq
	(*emptypb.Empty)(nil),     // 9: google.protobuf.Empty
}
var file_api_proto_v1_artist_proto_depIdxs = []int32{
	1,  // 0: artist.GetArtistReq.data:type_name -> artist.ArtistIdType
	0,  // 1: artist.GetArtistReply.data:type_name -> artist.ArtistType
	0,  // 2: artist.GetAllArtistReply.data:type_name -> artist.ArtistType
	0,  // 3: artist.CreateArtistReq.data:type_name -> artist.ArtistType
	1,  // 4: artist.CreateArtistReply.data:type_name -> artist.ArtistIdType
	0,  // 5: artist.ReplaceArtistReq.data:type_name -> artist.ArtistType
	1,  // 6: artist.DeleteArtistReq.data:type_name -> artist.ArtistIdType
	2,  // 7: artist.Artist.Get:input_type -> artist.GetArtistReq
	9,  // 8: artist.Artist.GetAll:input_type -> google.protobuf.Empty
	5,  // 9: artist.Artist.Create:input_type -> artist.CreateArtistReq
	7,  // 10: artist.Artist.Replace:input_type -> artist.ReplaceArtistReq
	8,  // 11: artist.Artist.Delete:input_type -> artist.DeleteArtistReq
	3,  // 12: artist.Artist.Get:output_type -> artist.GetArtistReply
	4,  // 13: artist.Artist.GetAll:output_type -> artist.GetAllArtistReply
	6,  // 14: artist.Artist.Create:output_type -> artist.CreateArtistReply
	9,  // 15: artist.Artist.Replace:output_type -> google.protobuf.Empty
	9,  // 16: artist.Artist.Delete:output_type -> google.protobuf.Empty
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_v1_artist_proto_init() }
func file_api_proto_v1_artist_proto_init() {
	if File_api_proto_v1_artist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_v1_artist_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ArtistType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_artist_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ArtistIdType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_artist_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetArtistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_artist_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetArtistReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_artist_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllArtistReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_artist_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateArtistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_artist_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CreateArtistReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_artist_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ReplaceArtistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_artist_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteArtistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_v1_artist_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_v1_artist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_artist_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_artist_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_artist_proto_msgTypes,
	}.Build()
	File_api_proto_v1_artist_proto = out.File
	file_api_proto_v1_artist_proto_rawDesc = nil
	file_api_proto_v1_artist_proto_goTypes = nil
	file_api_proto_v1_artist_proto_depIdxs = nil
}
